spring:
  config:
    activate:
      on-profile: local

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: info
    org:hibernate.SQL: info

